### ISSUE TITLE
Remove file.path.match(/json$/) and support inner objects

### ISSUE THREAD

**Issue by tamtakoe** [adamayres/gulp-wrap#20]
Check json format with JSON.parse (or other method), rather than a file extension, because I can generate json-object as js- or coffee-file then to wrap it in js or coffee.

If I use inner object I get `[object Object]`. You need to Stringify data in plugin

F.e.
```javascript
gulp.src('configs/')
  .pipe(generateConfigFiles('<%= projectName %>/config.js'))
  .pipe(wrap('define(["app"], function(app) {app.constant("config", <%= contents.public %>);});')))
  .pipe(gulp.dest('compiled/configs/'))
```

**Comment by shinnn** [comment]
I cannot understand what you'd like to do.

Could you show us an example of the change of `file.contents`? Like this:

```
AAAAAAA (source)
↓
BBBBBBB (after generateConfigFiles)
↓
CCCCCCC (after wrap)
↓
DDDDDDD (expected result)
```

**Comment by shinnn** [comment]
No feedback.

**Comment by tamtakoe** [comment]
Ok.
<pre>
[config.yaml](source)
"   public:
        param1: ...
        param2: ...,
        ..."
↓
[config.js](after generateConfigFiles) it is json content
"{
    "public": {
        "default.param0": "...",
        "param1": "...",
        "param2": "...",
        ...
    }
}"
↓
[config.js](after wrap) I use <%= contents.public %>
define(["app"], function(app) {
    app.constant("config", { "default.param0": "...",
                                          "param1": "...",
                                          "param2": "...",
                                          ...
                                        }"
    );
});'
↓
[config.js](expected result)
<contents shown above>
</pre>

Now I can't use config.js with json content because plugin only works with json files. I need to use gulp.rename. It will be good if I can specify to wrap options what type of content is expected.

**Comment by shinnn** [comment]
Is `generateConfigFiles` a transform stream you wrote, or a gulp plugin registered in npm?

**Comment by shinnn** [comment]
> I need to create config.json and use gulp.rename after wrap.

This seems appropriate.

**Comment by tamtakoe** [comment]
`generateConfigFiles` is my plugin. Now I make and use param `generateConfigFiles({section: 'public'})`, but it is less clearly and universal then `<%= contents.public %>`.
