### ISSUE TITLE
Show exception if data doesn't exist

### ISSUE THREAD

**Issue by tamtakoe** [adamayres/gulp-wrap#22]
Show exception if data doesn't exist

`gulpWrap('<%= data.value %>')` crashes without warning

**Comment by shinnn** [comment]
Can you elaborate on "data doesn't exist"?

**Comment by shinnn** [comment]
@tamtakoe ping

**Comment by shinnn** [comment]
No feedback.

**Comment by tamtakoe** [comment]
Sorry. Plugin doesn't throw errors from templates. 

```js
gulp.task('test', function(callback) {
    gulp.src(<src path>)
        .pipe(require('gulp-wrap')('<%= aaa.bbb %>'));
        .pipe(gulp.dest(<dest path>))
})
```
It works without errors but destination file not write

**Comment by shinnn** [comment]
Ok I confirmed a bug.

**Comment by shinnn** [comment]
https://github.com/adamayres/gulp-wrap/issues/23#issuecomment-93024875

> I plan to maintain it still

**Comment by shinnn** [comment]
@adamayres Any updates?

> I plan to maintain it still

**Comment by adamayres** [comment]
Happy to accept any PRs for a fix, otherwise might be some time before I get to it.

**Comment by shinnn** [comment]
@adamayres 

> **adamayres** was assigned by **shinnn** on 24 Apr

**Comment by adamayres** [comment]
@shinnn By maintain I meant that I would occasionally contribute and always review any PR's that come in. You can keep asking me the same question or trying to throw it in my face but things are not going to change on my end. If you would like to create a PR for this specific issue then I would be happy to review, or you can fork this repo and maintain it there. Your passive aggressive comments do nothing more than deter me from wanting to contribute.

Happy 4th of July!

**Comment by jdrydn** [comment]
Not sure if @shinnn added it or if @adamayres added it, but there is error-handling if you attach a listener for the `error` event:

```js
  .pipe(wrap('DO SOMETHING => <%= nmFn(file.path) %>').on('error', function (e) { console.error(e); }))
```

```
{ [ReferenceError: nmFn is not defined]
  name: 'ReferenceError',
  message: 'nmFn is not defined',
  stack: 'ReferenceError: nmFn is not defined\n    at eval (lodash.templateSources[0]:9:11)\n    at Function.exports.lodash.render (PROJECT/node_modules/consolidate/lib/consolidate.js:695:14)\n    at PROJECT/node_modules/gulp-wrap/index.js:66:37\n    at process._tickCallback (node.js:368:9)',
  showStack: false,
  showProperties: true,
  plugin: 'gulp-wrap' }
```

**Comment by adamayres** [comment]
Not sure if something has changed since you tried this, but on the latest version when I try something like this:

```javascript
gulp.task('wrap', function () {
  gulp.src('test.txt')
    .pipe(wrap('HELLO <% foo.bar %>'))
    .pipe(gulp.dest('.tmp'));
});
```

I get this when running the task:

```
$ gulp wrap
[16:39:32] Using gulpfile ~/dev/gulp-wrap/gulpfile.js
[16:39:32] Starting 'wrap'...
[16:39:32] Finished 'wrap' after 7.5 ms
Unhandled rejection ReferenceError: foo is not defined
    at eval (lodash.templateSources[0]:10:2)
    at /Users/adam.ayres/dev/gulp-wrap/node_modules/consolidate/lib/consolidate.js:779:16
    at /Users/adam.ayres/dev/gulp-wrap/node_modules/consolidate/lib/consolidate.js:143:5
    at Promise._execute (/Users/adam.ayres/dev/gulp-wrap/node_modules/bluebird/js/release/debuggability.js:272:9)
    at Promise._resolveFromExecutor (/Users/adam.ayres/dev/gulp-wrap/node_modules/bluebird/js/release/promise.js:473:18)
    at new Promise (/Users/adam.ayres/dev/gulp-wrap/node_modules/bluebird/js/release/promise.js:77:14)
    at promisify (/Users/adam.ayres/dev/gulp-wrap/node_modules/consolidate/lib/consolidate.js:136:10)
    at Function.exports.lodash.render (/Users/adam.ayres/dev/gulp-wrap/node_modules/consolidate/lib/consolidate.js:775:10)
    at /Users/adam.ayres/dev/gulp-wrap/index.js:73:37
    at process._tickCallback (internal/process/next_tick.js:103:7)
```

Please reopen with additional details if you are still able to reproduce.
