### ISSUE TITLE
Doesn't the author interested to maintain this plugin?

### ISSUE THREAD

**Issue by shinnn** [adamayres/gulp-wrap#23]
Hi, @adamayres.

I found that [you're not watching this project anymore](https://github.com/adamayres/gulp-wrap/watchers). You have no interest to maintain this project any more, right?

If you could transfer this repository to my account, I can keep on maintaining this project with more motivations :)

What do you think?

**Comment by adamayres** [comment]
Hey, not sure how the watch got removed. I plan to maintain it still, thx for the offer tho.
