### ISSUE TITLE
Cannot get the file name only

### ISSUE THREAD

**Issue by Gillardo** [adamayres/gulp-wrap#26]
Maybe i have missed something here but how can i get the file name only.  I do not want the full path, just the file name (including or excluding the extension, i dont mind)

**Comment by mallocator** [comment]
You can use file.relative if all your files are in the root of your source directory.

if that doesn't work check [this repo](https://github.com/gulpjs/vinyl) for more properties you can access.

**Comment by Gillardo** [comment]
Perfect, thank you

**Comment by Gillardo** [comment]
You may want to include that link on the readme file if it aint there already
